version: '3.4'

services:
  wirebreak.viewer:
    image: ${DOCKER_REGISTRY-}wirebreakviewer
    build:
      context: wirebreak-viewer-app
      dockerfile: Dockerfile
    ports:
    - "3001:80"

  map.viewer:
    image: ${DOCKER_REGISTRY-}mapviewer
    build:
      context: map-viewer-app
      dockerfile: Dockerfile
    ports:
    - "3000:80"

  shell.app:
    image: ${DOCKER_REGISTRY-}shellapp
    build:
      context: shell
      dockerfile: Dockerfile
    ports:
    - "4000:80"

